<div class="min-h-screen bg-slate-50">
    <div class="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8 space-y-6">
        <div class="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
            <div><a href="{{ route('monitor.usuarios.index') }}" wire:navigate class="text-xs font-bold text-indigo-600">← Monitoreo de usuarios</a><h1 class="mt-2 text-3xl font-black tracking-tight text-slate-900">{{ $perfil->alias }}</h1><p class="text-sm text-slate-500">Detalle de actividad del usuario monitoreado.</p></div>
            <div class="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-bold text-emerald-700">{{ $perfil->hash_fb ? 'Cuenta vinculada' : 'Vinculación pendiente' }}</div>
        </div>
        <section class="rounded-2xl border border-slate-200 bg-white shadow-sm">
            <div class="flex flex-col gap-3 border-b border-slate-100 px-6 py-5 sm:flex-row sm:items-center sm:justify-between"><div><h2 class="font-bold text-slate-900">Actividad del usuario</h2><p class="text-sm text-slate-500">Consulta y filtra la información importada.</p></div><select wire:model.live="dias" class="rounded-lg border-slate-300 text-sm"><option value="7">Últimos 7 días</option><option value="30">Últimos 30 días</option><option value="90">Últimos 90 días</option></select></div>
            <div class="grid gap-6 p-6 lg:grid-cols-2"><div><h3 class="text-sm font-bold text-slate-800">Actividad por hora</h3><div class="mt-5 flex h-48 items-end gap-1 border-b border-slate-100">@foreach($porHora as $h=>$total)<div class="group flex-1" title="{{ $h }}:00 — {{ $total }}"><div class="mx-auto w-full max-w-4 rounded-t bg-indigo-500 transition-all" style="height: {{ min(100, max(3, $total * 5)) }}%"></div></div>@endforeach</div><div class="mt-2 flex justify-between text-[10px] text-slate-400"><span>00h</span><span>06h</span><span>12h</span><span>18h</span><span>23h</span></div></div><div><h3 class="text-sm font-bold text-slate-800">Reacciones por tipo</h3><div class="mt-4 space-y-3">@forelse($porTipo as $r)<div><div class="flex justify-between text-xs"><span class="text-slate-600">{{ $r['etiqueta'] }}</span><strong>{{ $r['total'] }}</strong></div><div class="mt-1 h-2 rounded-full bg-slate-100"><div class="h-2 rounded-full bg-rose-400" style="width: {{ min(100, $r['total'] * 5) }}%"></div></div></div>@empty<p class="text-sm text-slate-400">No hay reacciones en el periodo.</p>@endforelse</div></div></div>
        </section>
        <section class="rounded-2xl border border-slate-200 bg-white shadow-sm"><div class="border-b border-slate-100 px-6 py-5"><h2 class="font-bold text-slate-900">Registros</h2></div><div class="overflow-x-auto"><table class="min-w-full text-left text-sm"><thead class="bg-slate-50 text-xs uppercase tracking-wider text-slate-500"><tr><th class="px-6 py-3">Fecha</th><th class="px-6 py-3">Información</th></tr></thead><tbody class="divide-y divide-slate-100">@forelse($registros as $registro)<tr><td class="whitespace-nowrap px-6 py-4 text-slate-500">{{ optional($registro->fecha ?? $registro->agregado_en)->format('d/m/Y H:i') }}</td><td class="px-6 py-4 text-slate-700">{{ $registro->texto ?? $registro->objetivo ?? $registro->descripcion ?? $registro->nombre ?? 'Registro de actividad' }}</td></tr>@empty<tr><td colspan="2" class="px-6 py-8 text-center text-slate-500">No hay registros para este periodo.</td></tr>@endforelse</tbody></table></div><div class="px-6 py-4">{{ $registros->links() }}</div></section>
    </div>
</div>
